// Generates src/generated/plugin-registry.ts from the plugin manifests (2.F1).
//
// Scans src/plugins/{scrapers,notifiers}/*/manifest.json, keeps the enabled ones
// that ship a frontend (entry + route_base), and writes a typed registry mapping
// route_base -> lazy component/i18n imports via the `$plugins` alias.
//
// FDISC-R1: the output is generated, never hand-edited. Runs automatically on
// predev/prebuild/precheck; run manually with `npm run build:plugins`.

import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import process from 'node:process';
import { fileURLToPath, pathToFileURL } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url)); // src/frontend/scripts
const REPO_ROOT = join(HERE, '..', '..', '..');
const PLUGINS_ROOT = join(REPO_ROOT, 'src', 'plugins');
const OUT_FILE = join(HERE, '..', 'src', 'generated', 'plugin-registry.ts');
const FOLDERS = ['scrapers', 'notifiers'];

function stripModuleExt(path) {
	return path.replace(/\.(ts|js|mjs|svelte)$/i, '');
}

/** Collect the enabled, UI-bearing plugins under `root`, sorted by folder+name. */
export function collectPlugins(root) {
	const entries = [];
	for (const folder of FOLDERS) {
		const base = join(root, folder);
		if (!existsSync(base) || !statSync(base).isDirectory()) continue;
		for (const name of readdirSync(base).sort()) {
			const dir = join(base, name);
			if (!statSync(dir).isDirectory()) continue;
			const manifestPath = join(dir, 'manifest.json');
			if (!existsSync(manifestPath)) continue;
			let manifest;
			try {
				manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
			} catch (err) {
				console.warn(`build:plugins: skipping ${folder}/${name}: bad manifest (${err.message})`);
				continue;
			}
			if (manifest.enabled !== true) continue;
			const fe = manifest.frontend;
			if (!fe || !fe.entry || !fe.route_base) continue; // no own UI (e.g. notifiers)
			entries.push({
				name: manifest.name,
				route_base: fe.route_base,
				component: `$plugins/${folder}/${name}/${stripModuleExt(fe.entry)}`,
				i18n: fe.i18n ? `$plugins/${folder}/${name}/${fe.i18n}` : null
			});
		}
	}
	return entries;
}

/** Render the generated TypeScript module for the given entries. */
export function renderRegistry(entries) {
	const lines = [
		'// AUTOGENERATED by scripts/build-plugins.mjs - do not edit by hand (FDISC-R1).',
		'// Regenerate with `npm run build:plugins` (runs on predev/prebuild/precheck).',
		'',
		'export interface GeneratedPlugin {',
		'\tname: string;',
		'\troute_base: string;',
		'\tcomponent: () => Promise<unknown>;',
		'\ti18n: (() => Promise<unknown>) | null;',
		'}',
		'',
		'export const plugins: GeneratedPlugin[] = ['
	];
	for (const entry of entries) {
		const i18n = entry.i18n ? `() => import(${JSON.stringify(entry.i18n)})` : 'null';
		lines.push(
			'\t{',
			`\t\tname: ${JSON.stringify(entry.name)},`,
			`\t\troute_base: ${JSON.stringify(entry.route_base)},`,
			`\t\tcomponent: () => import(${JSON.stringify(entry.component)}),`,
			`\t\ti18n: ${i18n}`,
			'\t},'
		);
	}
	lines.push('];', '');
	return lines.join('\n');
}

/** Generate the registry file; returns the collected entries. */
export function generate(root = PLUGINS_ROOT, out = OUT_FILE) {
	const entries = collectPlugins(root);
	mkdirSync(dirname(out), { recursive: true });
	writeFileSync(out, renderRegistry(entries), 'utf8');
	return entries;
}

// Run only when invoked directly (not when imported by tests).
if (import.meta.url === pathToFileURL(process.argv[1]).href) {
	const entries = generate();
	console.log(`build:plugins: generated ${entries.length} plugin(s) -> ${OUT_FILE}`);
}
